#!/bin/sh

DIR=/usr/bin
DAEMON=$DIR/seamlessync-daemon
DAEMON_NAME=seamlessync-daemon

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=$(users | awk {'print $1'})

PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

if [ "$(status_of_proc $DAEMON_NAME $DAEMON | grep 'is running' | awk {'print $3'})" = "is" ]; then

log_daemon_msg "Stopping system $DAEMON_NAME daemon"
start-stop-daemon --stop --pidfile $PIDFILE --retry 5
log_end_msg $?

fi

#MyPATH = /usr/bin/seamlessync
#PythonPATH = /usr/bin/python

#kill $(cat /home/aaditya/serverpid.txt)
#if [ -x $MyPATH ]; then
#$PythonPATH $MyPATH stop
#fi
